[package]
name = "fuurin"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.74.0" # clap

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
cursive = "0.21.1"
rodio = { version = "0.21.1", default-features = false, features = ["lewton", "playback"] }
